# Generated by Django 4.2.2 on 2023-06-14 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('futbk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Geo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=4, max_digits=10)),
                ('long', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='futuser',
            name='country',
        ),
        migrations.RemoveField(
            model_name='futuser',
            name='state',
        ),
        migrations.RemoveField(
            model_name='futuser',
            name='street',
        ),
        migrations.RemoveField(
            model_name='futuser',
            name='street_no',
        ),
        migrations.RemoveField(
            model_name='futuser',
            name='zip_code',
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='Nigeria', max_length=100)),
                ('state', models.CharField(default='Lagos', max_length=100)),
                ('street', models.CharField(max_length=100, null=True)),
                ('street_no', models.SmallIntegerField(null=True)),
                ('zip_code', models.CharField(max_length=10, null=True)),
                ('geo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='futbk.geo')),
            ],
        ),
        migrations.AddField(
            model_name='futuser',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='futbk.address'),
        ),
    ]
