# Generated by Django 4.2.2 on 2023-06-14 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futbk', '0002_geo_remove_futuser_country_remove_futuser_state_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmark',
            options={'ordering': ['date']},
        ),
        migrations.AddField(
            model_name='bookmark',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='follow',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='like',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='republish',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='view',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='base',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together={('post', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('follower', 'followed')},
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('post', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='post',
            unique_together={('text', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='reply',
            unique_together={('text', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='republish',
            unique_together={('post', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='view',
            unique_together={('post', 'user')},
        ),
    ]
