# Generated by Django 4.2.2 on 2023-06-15 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futbk', '0003_alter_bookmark_options_bookmark_date_follow_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='futuser',
            name='occupation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='futuser',
            name='tag_line',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
