# Generated by Django 4.2.2 on 2023-06-15 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('futbk', '0004_futuser_occupation_futuser_tag_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='base',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='futbk.base'),
        ),
    ]
