# Generated by Django 4.2.2 on 2023-06-15 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futbk', '0005_alter_post_base'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='msg_reciever',
            new_name='msg_receiver',
        ),
        migrations.AddField(
            model_name='view',
            name='ip_address',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
