# Generated by Django 4.2.2 on 2023-06-15 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futbk', '0006_rename_msg_reciever_message_msg_receiver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.CharField(default='Agege', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(default='Nigeria', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(default='Lagos', max_length=100, null=True),
        ),
    ]
