# Generated by Django 4.2.2 on 2023-06-16 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('futbk', '0007_address_city_alter_address_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='msg_receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receiver', to=settings.AUTH_USER_MODEL),
        ),
    ]
