# Generated by Django 4.2.2 on 2023-06-17 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futbk', '0008_alter_message_msg_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='parent',
            field=models.ManyToManyField(null=True, to='futbk.post'),
        ),
        migrations.AddField(
            model_name='post',
            name='reply',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
