# Generated by Django 4.2.2 on 2023-06-17 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futbk', '0009_post_parent_post_reply_delete_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base',
            name='base_banner',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='base',
            name='base_img',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='futuser',
            name='profile_banner',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='futuser',
            name='profile_img',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='parent',
            field=models.ManyToManyField(to='futbk.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.URLField(null=True),
        ),
    ]
