# Generated by Django 4.2.2 on 2023-06-18 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futbk', '0010_alter_base_base_banner_alter_base_base_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='futuser',
            name='age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
