# Generated by Django 4.2.2 on 2023-06-18 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futbk', '0011_futuser_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futuser',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('R', 'Rather Not Say')], default='R', max_length=1),
        ),
    ]
