# Generated by Django 4.2.2 on 2023-06-18 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('futbk', '0012_alter_futuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futuser',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='futbk.address'),
        ),
        migrations.AlterField(
            model_name='futuser',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='futuser',
            name='profile_banner',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='futuser',
            name='profile_img',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='futuser',
            name='tag_line',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
