# Generated by Django 4.2.2 on 2023-06-18 20:56

from django.db import migrations
import futbk.manager


class Migration(migrations.Migration):

    dependencies = [
        ('futbk', '0013_alter_futuser_address_alter_futuser_occupation_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='futuser',
            managers=[
                ('objects', futbk.manager.FutUserManager()),
            ],
        ),
    ]
