# Generated by Django 4.2.2 on 2023-06-19 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futbk', '0014_alter_futuser_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geo',
            name='lat',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
        migrations.AlterField(
            model_name='geo',
            name='long',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='video',
            field=models.URLField(),
        ),
    ]
